# syntax=docker/dockerfile:1.4
# Generated by scripts/05-setup-repo.sh.
# Based on the official Shopware production Docker approach.

ARG PHP_VERSION={{PHP_VERSION}}
ARG ADDITIONAL_PHP_EXTENSIONS="redis amqp"

FROM ghcr.io/shopware/docker-base:${PHP_VERSION}-frankenphp AS base-image
USER root
RUN if [ -n "$ADDITIONAL_PHP_EXTENSIONS" ]; then install-php-extensions $ADDITIONAL_PHP_EXTENSIONS; fi
USER www-data

FROM ghcr.io/shopware/shopware-cli:latest-php-${PHP_VERSION} AS shopware-cli

FROM shopware-cli AS build
ADD . /src
WORKDIR /src
RUN --mount=type=secret,id=packages_token,env=SHOPWARE_PACKAGES_TOKEN \
    --mount=type=secret,id=composer_auth,dst=/src/auth.json \
    --mount=type=cache,target=/root/.composer \
    --mount=type=cache,target=/root/.npm \
    /usr/local/bin/entrypoint.sh shopware-cli project ci /src

FROM base-image AS final
COPY --from=build --chown=82 --link /src /var/www/html
