APP_ENV=prod
APP_SECRET={{APP_SECRET}}
APP_URL={{APP_URL}}
SALES_CHANNEL_URL={{APP_URL}}
DATABASE_URL=mysql://{{DB_USER}}:{{DB_PASSWORD}}@database:3306/{{DB_NAME}}

INSTALL_LOCALE={{INSTALL_LOCALE}}
INSTALL_CURRENCY={{INSTALL_CURRENCY}}
INSTALL_ADMIN_USERNAME={{INSTALL_ADMIN_USERNAME}}
INSTALL_ADMIN_PASSWORD={{INSTALL_ADMIN_PASSWORD}}
INSTALL_ADMIN_EMAIL={{ADMIN_EMAIL}}
SHOPWARE_USAGE_DATA_CONSENT={{SHOPWARE_USAGE_DATA_CONSENT}}
SHOPWARE_DEPLOYMENT_STAGING={{SHOPWARE_DEPLOYMENT_STAGING}}
SHOPWARE_DEPLOYMENT_TIMEOUT=900

COMPOSER_PLUGIN_LOADER=1
SHOPWARE_HTTP_CACHE_ENABLED=1
TRUSTED_PROXIES=127.0.0.1,REMOTE_ADDR

REDIS_URL=redis://:{{REDIS_PASSWORD}}@redis:6379/0
CACHE_URL=redis://:{{REDIS_PASSWORD}}@redis:6379/1
PHP_SESSION_HANDLER=redis
PHP_SESSION_SAVE_PATH=tcp://redis:6379?auth={{REDIS_PASSWORD}}

MESSENGER_TRANSPORT_DSN=amqp://{{RABBITMQ_USER}}:{{RABBITMQ_PASSWORD}}@rabbitmq:5672/%2f/messages
MESSENGER_TRANSPORT_LOW_PRIORITY_DSN=amqp://{{RABBITMQ_USER}}:{{RABBITMQ_PASSWORD}}@rabbitmq:5672/%2f/low_priority
MESSENGER_TRANSPORT_FAILURE_DSN=amqp://{{RABBITMQ_USER}}:{{RABBITMQ_PASSWORD}}@rabbitmq:5672/%2f/failed

S3_ENDPOINT={{S3_ENDPOINT}}
S3_REGION={{S3_REGION}}
S3_USE_PATH_STYLE={{S3_USE_PATH_STYLE}}
S3_PUBLIC_BUCKET={{S3_PUBLIC_BUCKET}}
S3_PRIVATE_BUCKET={{S3_PRIVATE_BUCKET}}
S3_PUBLIC_URL={{S3_PUBLIC_URL}}
S3_ACCESS_KEY={{S3_ACCESS_KEY}}
S3_SECRET_KEY={{S3_SECRET_KEY}}

SHOPWARE_STORE_ACCOUNT_EMAIL={{SHOPWARE_STORE_ACCOUNT_EMAIL}}
SHOPWARE_STORE_ACCOUNT_PASSWORD={{SHOPWARE_STORE_ACCOUNT_PASSWORD}}
SHOPWARE_STORE_SHOP_SECRET={{SHOPWARE_STORE_SHOP_SECRET}}
SHOPWARE_STORE_LICENSE_DOMAIN={{SHOPWARE_STORE_LICENSE_DOMAIN}}

PROJECT_SLUG={{PROJECT_SLUG}}
ENVIRONMENT={{ENVIRONMENT}}
SHOPWARE_IMAGE={{SHOPWARE_IMAGE}}
