APP_ENV={{APP_ENV|dotenv}}
APP_SECRET={{APP_SECRET|dotenv}}
APP_URL={{APP_URL|dotenv}}
SALES_CHANNEL_URL={{APP_URL|dotenv}}
DATABASE_URL={{DATABASE_URL|dotenv}}

COMPOSER_PLUGIN_LOADER="1"
SHOPWARE_HTTP_CACHE_ENABLED="1"
TRUSTED_PROXIES="127.0.0.1,REMOTE_ADDR"

REDIS_URL={{REDIS_URL|dotenv}}
CACHE_URL={{CACHE_URL|dotenv}}
PHP_SESSION_HANDLER="redis"
PHP_SESSION_SAVE_PATH={{PHP_SESSION_SAVE_PATH|dotenv}}

MESSENGER_TRANSPORT_DSN={{MESSENGER_TRANSPORT_DSN|dotenv}}
MESSENGER_TRANSPORT_LOW_PRIORITY_DSN={{MESSENGER_TRANSPORT_LOW_PRIORITY_DSN|dotenv}}
MESSENGER_TRANSPORT_FAILURE_DSN={{MESSENGER_TRANSPORT_FAILURE_DSN|dotenv}}

S3_ENDPOINT={{S3_ENDPOINT|dotenv}}
S3_REGION={{S3_REGION|dotenv}}
S3_USE_PATH_STYLE={{S3_USE_PATH_STYLE|dotenv}}
S3_PUBLIC_BUCKET={{S3_PUBLIC_BUCKET|dotenv}}
S3_PRIVATE_BUCKET={{S3_PRIVATE_BUCKET|dotenv}}
S3_PUBLIC_URL={{S3_PUBLIC_URL|dotenv}}
S3_ACCESS_KEY={{S3_ACCESS_KEY|dotenv}}
S3_SECRET_KEY={{S3_SECRET_KEY|dotenv}}

PROJECT_SLUG={{PROJECT_SLUG|dotenv}}
ENVIRONMENT={{ENVIRONMENT|dotenv}}
