# Generated by scripts/05-setup-repo.sh.
# Uses Shopware's S3-compatible filesystem adapter.
shopware:
  filesystem:
    public: &s3_public
      type: "amazon-s3"
      url: "%env(S3_PUBLIC_URL)%"
      config:
        bucket: "%env(S3_PUBLIC_BUCKET)%"
        region: "%env(S3_REGION)%"
        endpoint: "%env(S3_ENDPOINT)%"
        use_path_style_endpoint: "%env(bool:S3_USE_PATH_STYLE)%"
        credentials:
          key: "%env(S3_ACCESS_KEY)%"
          secret: "%env(S3_SECRET_KEY)%"
    private:
      type: "amazon-s3"
      visibility: "private"
      config:
        bucket: "%env(S3_PRIVATE_BUCKET)%"
        region: "%env(S3_REGION)%"
        endpoint: "%env(S3_ENDPOINT)%"
        use_path_style_endpoint: "%env(bool:S3_USE_PATH_STYLE)%"
        credentials:
          key: "%env(S3_ACCESS_KEY)%"
          secret: "%env(S3_SECRET_KEY)%"
    theme: *s3_public
    asset: *s3_public
    sitemap: *s3_public
