# Generated by scripts/05-setup-repo.sh.
# Config for Shopware 6.6/6.7 reverse proxy cache using the official Shopware Varnish image.
shopware:
  http_cache:
    reverse_proxy:
      enabled: true
      hosts:
        - varnish
