# Generated by scripts/05-setup-repo.sh.
# Config for Shopware 6.7 reverse proxy cache using the official Shopware Varnish image.
shopware:
  http_cache:
    reverse_proxy:
      enabled: true
      ban_method: "BAN"
      hosts:
        - "http://varnish"
      max_parallel_invalidations: 3
      use_varnish_xkey: true
